CREATE SCHEMA IF NOT EXISTS `SPRINGBOOTEX` DEFAULT CHARACTER SET utf8;
CREATE USER IF NOT EXISTS 'testuser'@'localhost' IDENTIFIED BY 'testuser!';
GRANT ALL PRIVILEGES ON `SPRINGBOOTEX`. * TO 'testuser'@'localhost' IDENTIFIED BY 'testuser!' WITH GRANT OPTION;
FLUSH PRIVILEGES;