CREATE SCHEMA IF NOT EXISTS `todozer` DEFAULT CHARACTER SET utf8;
CREATE USER IF NOT EXISTS 'dozer'@'localhost' IDENTIFIED BY 'BraveDoZer!';
GRANT ALL PRIVILEGES ON `todozer`. * TO 'dozer'@'localhost' IDENTIFIED BY 'BraveDoZer!' WITH GRANT OPTION;
FLUSH PRIVILEGES;